In [3]:
from google.colab import drive
import pandas as pd
import numpy as np
import os

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
path = '/content/drive/MyDrive/Mod3Clase1/'
list_files = os.listdir(path)
list_files

['Reto_03_Student_Performance.csv',
 'Reto_02_Salary_Professions.csv',
 'Reto_01_Laptops_Dataset.csv',
 'M03_S01_datasets_descrip.pdf',
 'Ejemplo_01_Titanic_Dataset.csv']

In [6]:
df = pd.read_csv(os.path.join(path, "Ejemplo_01_Titanic_Dataset.csv"))
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Media

In [7]:
promedio_edad = df["Age"].mean()
promedio_edad

30.272590361445783

Mediana

In [8]:
mediana_edad = df["Age"].median()
mediana_edad

27.0

Moda

In [9]:
moda_edad = df ["Age"].mode()
moda_edad

0    21.0
1    24.0
Name: Age, dtype: float64

In [10]:
df = pd.read_csv(os.path.join(path, "Reto_01_Laptops_Dataset.csv"))
df

,brand,name,price,spec_score,user_votes,user_rating,os,utility: Business,utility: Everyday Use,utility: Performance,...,processor_gen,processor_brand,processor_core,base_processor_speed_GHz,turbo_processor_speed_GHz,no_cores,cache_memory_mb,graphics_brand,rom_capacity_gb,internal_memory_gb
0,hp,Victus 15-fb0157AX Gaming,49800.0,70.0,97.0,4.3,windows 11,0,0,0,...,5.0,amd,Ryzen 5,3.3,4.2,6.0,16.0,amd,8.0,512.0
1,xiaomi,Redmi G Pro 2024 Gaming,102990.0,78.0,71.0,4.3,windows 11,0,0,0,...,14.0,intel,Core i9,2.2,5.8,24.0,36.0,nvidia,16.0,1024.0
2,tecno,Megabook T1,23990.0,56.0,177.0,4.4,windows 11,0,0,1,...,11.0,intel,Core i3,3.0,4.1,2.0,6.0,intel,8.0,512.0
3,samsung,Galaxy Book2 Pro 13,62990.0,60.0,1511.0,4.5,windows 11,0,1,0,...,12.0,intel,Core i5,1.7,4.4,12.0,12.0,intel,16.0,512.0
4,apple,MacBook Air 2020 MGND3HN,79990.0,43.0,20380.0,4.7,mac,0,0,1,...,1.0,apple,NaN,NaN,3.2,8.0,NaN,apple,8.0,256.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,dell,Vostro 3420 D552317WIN9B,51199.0,55.0,84.0,4.1,windows 11,0,1,0,...,12.0,intel,Core i5,1.3,4.4,10.0,12.0,intel,8.0,512.0
993,hp,Spectre x360 16-f2005TX,185990.0,84.0,59.0,4.1,windows 11,0,0,1,...,13.0,intel,Core i7,2.2,5.0,12.0,18.0,intel,32.0,1024.0
994,hp,Spectre x360 2023 13.5-ef2033TU,139990.0,68.0,111.0,4.5,windows 11,0,0,1,...,13.0,intel,Core i7,NaN,5.0,10.0,12.0,intel,16.0,1024.0
995,huawei,MateBook D14 2023,58999.0,62.0,110.0,4.7,windows 11,0,0,0,...,13.0,intel,Core i5,1.9,4.6,12.0,12.0,intel,16.0,512.0
996,huawei,MateBook D16 2023,84999.0,59.0,84.0,4.2,windows 11,0,0,0,...,13.0,intel,Core i5,NaN,4.7,12.0,18.0,intel,8.0,512.0

In [15]:
promedio_precio = df["price"].mean()
promedio_precio

84889.24974924774

In [16]:
mediana_precio = df["price"].median()
mediana_precio

64690.0

In [17]:
moda_precio = df ["price"].mode()
moda_precio

0    59990.0
Name: price, dtype: float64

In [19]:
df["price"].unique()

array([ 49800., 102990.,  23990.,  62990.,  79990.,  26780.,  35990.,
        54990.,  52990.,  99900.,  32990.,  81490.,  24990.,  33990.,
        26749.,  58990.,  74990.,  39990.,  43990.,  56490.,  59990.,
       114900.,  99990.,  49990.,  42990.,  55390.,  89999.,  84990.,
        33790.,  27990.,  44990.,  65990.,  77990., 120900.,  19979.,
        89990.,  25680.,  37990.,  69999.,  46990.,  72990.,   8000.,
       154900., 134225., 146990.,  63490., 191668.,  75990., 329990.,
       135999.,  51990.,  36990.,  34880., 137990., 599990., 149990.,
       199990.,  84700., 399900., 186899.,  24790.,  69990.,  41990.,
        35900.,  64690.,  71990.,  35091.,  48490.,  53990.,  53999.,
        19990.,  35790.,  73990.,  12990.,  18990.,  76990.,  54790.,
        36890.,  86990.,  36280.,  31990.,  64990.,  57990.,  70490.,
        89900.,  52999., 112990.,  68990.,  68490., 104990.,  94990.,
        74490., 489883.,  46490., 108000.,  17990.,  69890., 184999.,
       449990., 120490.,  87990.,  30700., 162990., 229990., 113861.,
       119990., 107990., 104072., 114990., 299990., 109990., 133999.,
       134900., 174900.,  78990.,  96999.,  81990., 103990., 111990.,
       249990., 225862., 279990.,  21990., 349990.,  67490., 138990.,
       163990., 122990., 179990.,  73882.,  35500., 169990., 159990.,
        47990., 139990., 171990., 131990., 141990., 181990., 289990.,
       189990.,  96990., 297758.,  25990., 106000.,  62479., 102900.,
        55990.,  97990.,  82990., 195990.,  56990.,  38249., 115999.,
       101990.,  28190.,  22090.,  59490.,  59997.,  58500.,  49490.,
        24900.,  26990.,  72000., 174490.,  49199., 176499.,  20990.,
        60990.,  73223.,  34990.,  15990.,  83990., 187490.,  80650.,
        26490., 113999., 151490.,  57000., 199999.,  35490.,  49999.,
        48900.,  40490., 149900.,  63499.,  81999., 299999.,  81400.,
        62490.,  80999.,  34490.,  35999.,  52199.,  67990.,  87190.,
       129900.,  72190., 148990.,  67900.,  31500., 519990.,  50000.,
       218990.,  30834.,  44750., 102999., 230590., 224990., 176490.,
       349900., 289690., 123190.,  50790.,  58900.,  50390.,  98790.,
        19999., 154990., 106590.,  90223.,  38990.,  45990.,  93990.,
        58999.,  59900.,  38790.,  88990.,  52850., 124999.,  52890.,
        50990.,  66990.,  91190.,  32790., 132190.,  34821.,  33290.,
        16490.,  53490.,  33118.,  45890.,  53499.,  36490.,  49921.,
       339999.,  11990.,  27490.,  63990.,  20000.,  40990., 151990.,
       168025.,  80990.,  80190.,  59290., 139190., 298990., 164190.,
       103395.,  39390.,  89190., 121000.,  33350.,  61712.,  50490.,
        95689.,  44890.,  63889.,  52499.,  55700.,  28990., 239990.,
       271990.,  36499.,  44490.,  64490.,  43590.,  66450., 124000.,
        47490.,  35499.,  86190.,  94599., 114190., 128990.,  98000.,
       130990.,  26100., 415000.,  59856.,  72490.,  62500.,  34890.,
        94190.,  23999.,  62190.,  81088., 399999., 130000.,  14990.,
        40739.,  38999.,  60190.,  69190.,  59190.,  61000.,  43400.,
        85990.,  41200.,  48290., 153490.,  34000.,  52010.,  29990.,
        61990.,  70190., 219990.,  67190.,  51000.,  36700.,  85190.,
        84190.,  48990.,  39490., 106499.,  45490.,  87490.,  68999.,
        90990., 134990., 100990., 110990., 237990., 109490., 183990.,
        80490.,  36500.,  56190., 231746.,  32999.,  54559.,  36790.,
        92990., 344990., 126499., 100190., 116990., 132490., 113090.,
        31890., 222990.,  96490., 257490.,  60200.,  14701., 159999.,
        90000., 150000.,  61490., 322190., 453990., 199290., 448690.,
        75190., 129990.,  65190.,  41199., 303290., 121860.,  42600.,
        41400.,  31490.,  78299., 261921., 390914.,  22490., 373192.,
       111422.,  96700., 117899., 152499.,  78980.,  86730.,  70790.,
        23940.,  47890.,  52400.,  69345., 108990.,  86490.,  95990.,
        30990.,  88490.,  58490.,  85600.,  32390.,  50999.,  69490.,
       115558.,  58400., 117000.,  56267.,  84899.,  79999.,  83500.,
        46899.,  31899., 104989.,  70990.,  38900., 279490., 202490.,
       303490., 355490., 157544., 286200., 142190.,  32500., 125000.,
        89799.,  16990.,  56999., 199900.,  54199.,  35083.,  95790.,
        65899.,  32490.,  45900.,  43980.,  56900.,  55999., 158990.,
       166490., 156990.,  27590.,  99950., 210990., 131590., 172990.,
        52299.,  67890.,  34200.,  63290., 247999., 292990.,  94490.,
        62842.,  27499.,  27390.,  44799.,  58800.,  62687.,  54299.,
        71999., 107399., 149999.,  38490., 102490., 122638., 178490.,
       106990.,  55800.,  39800.,  88999.,  54900., 132900., 142990.,
       251041., 198999.,  47250., 162000., 220990., 224790.,  58890.,
       184990.,  62590.,  61690.,  54271., 105299., 234990., 159450.,
       155500.,  78490.,  81000., 386990., 366190.,  36800.,  87890.,
        45399.,  75999.,  47999.,  41800.,  93566.,  35290.,  34980.,
       118300.,  98990.,  47237.,  51899., 209990., 264990., 133990.,
       144990., 126990.,  99399., 109900.,  95700.,  21390.,  42100.,
        59890.,  51199., 185990.,  84999.])

In [20]:
df ["price"].mode()

0    59990.0
Name: price, dtype: float64

In [21]:
df ["price"].max()

599990.0

Varianza

In [26]:
varianza_fare = df["Fare"].var()
varianza_fare

3125.6570743195775

In [31]:
desviacion_estandar_fare = df["Fare"].std()
desviacion_estandar_fare

55.90757617997383

In [32]:
df["Fare"].mean()

35.627188489208635

Rango

In [8]:
edad_max = df["Age"].max()
edad_min = df["Age"].min()

In [9]:
Edad_rango = edad_max - edad_min

In [10]:
from scipy import stats